version: '3.8'

services:
  gateway:
    image: tampler/nws-api-gateway
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        SSH_PRIV_KEY: ${SSH_PRIV_KEY}
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8084:8084
    volumes:
      - ./configs/app.toml:/app/configs/app.toml:ro
      - ./configs/nats:/app/configs/nats:ro
    environment:
      - XDG_CONFIG_HOME=/app/configs
      - NATS_URL=192.168.1.93:1111
      - NATS_USER=local
      - NATS_PASS=
    external_links:
      - sdk
