// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package api

// Defines values for MandatoryAction.
const (
	Create  MandatoryAction = "Create"
	Delete  MandatoryAction = "Delete"
	List    MandatoryAction = "List"
	Nuke    MandatoryAction = "Nuke"
	Read    MandatoryAction = "Read"
	Resolve MandatoryAction = "Resolve"
	Update  MandatoryAction = "Update"
)

// Error defines model for Error.
type Error struct {
	// Error code
	Code int32 `json:"code"`

	// Error message
	Message string `json:"message"`
}

// Mandatory defines model for Mandatory.
type Mandatory struct {
	Action  MandatoryAction `json:"Action" validate:"required"`
	Command string          `json:"Command" validate:"required"`
	Params  []string        `json:"Params"`
}

// MandatoryAction defines model for Mandatory.Action.
type MandatoryAction string

// Metrics defines model for Metrics.
type Metrics = []string

// Options defines model for Options.
type Options struct {
	Exclude *[]string `json:"Exclude,omitempty"`
}

// Req defines model for Req.
type Req struct {
	Mandatory Mandatory `json:"Mandatory"`
	Options   *Options  `json:"Options,omitempty"`
}

// Success defines model for Success.
type Success struct {
	Data  []byte `json:"data"`
	Err   string `json:"err"`
	Jobid string `json:"jobid"`
}

// ServerError defines model for ServerError.
type ServerError = Error

// PostV1JSONRequestBody defines body for PostV1 for application/json ContentType.
type PostV1JSONRequestBody = Req
