// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package api

// Defines values for MandatoryAction.
const (
	MandatoryActionCreate MandatoryAction = "Create"

	MandatoryActionDelete MandatoryAction = "Delete"

	MandatoryActionList MandatoryAction = "List"

	MandatoryActionNuke MandatoryAction = "Nuke"

	MandatoryActionRead MandatoryAction = "Read"

	MandatoryActionResolve MandatoryAction = "Resolve"

	MandatoryActionUpdate MandatoryAction = "Update"
)

// Defines values for OptionsZone.
const (
	OptionsZoneDefault OptionsZone = "default"

	OptionsZoneRuMsk0 OptionsZone = "ru-msk-0"
)

// Error defines model for Error.
type Error struct {
	// Error code
	Code int32 `json:"code"`

	// Error message
	Message string `json:"message"`
}

// Mandatory defines model for Mandatory.
type Mandatory struct {
	Action  MandatoryAction `json:"Action" validate:"required"`
	Command string          `json:"Command" validate:"required"`
}

// MandatoryAction defines model for Mandatory.Action.
type MandatoryAction string

// Metrics defines model for Metrics.
type Metrics []string

// Options defines model for Options.
type Options struct {
	Exclude *[]string    `json:"Exclude,omitempty"`
	Params  *[]string    `json:"Params,omitempty"`
	Zone    *OptionsZone `json:"Zone,omitempty"`
}

// OptionsZone defines model for Options.Zone.
type OptionsZone string

// Request defines model for Request.
type Request struct {
	Mandatory Mandatory `json:"Mandatory"`
	Options   *Options  `json:"Options,omitempty"`
}

// Success defines model for Success.
type Success struct {
	Api     string `json:"Api"`
	Data    []byte `json:"Data"`
	Service string `json:"Service"`
}

// ServerError defines model for ServerError.
type ServerError Error

// PostV1JSONBody defines parameters for PostV1.
type PostV1JSONBody Request

// PostV1JSONRequestBody defines body for PostV1 for application/json ContentType.
type PostV1JSONRequestBody PostV1JSONBody
