# Full app config
[common]
debug = true

[auth]
auth_enabled = false

[http]
auth_file = "/tmp/app.json"
pem_file = "/tmp/token_jwt_key.pem"
port = 8084

body_limit = "4K"
max_rps = 20

allow_timeout = false
timeout = 300

allow_compress = false
compress_level = 5

[debug]
dump_on_error = false
metrics_name = "api_gateway"

[nats]
server = "nats://hyp:4222"
timeout = 25
topic = "command.ingress"
