# Full app config

[http]
port = 8084
auth_file = "/tmp/app.json"
pem_file = "/tmp/token_jwt_key.pem"

body_limit = "4K"
max_rps = 20

allow_timeout = false
timeout = 300

allow_compress = false
compress_level = 5

[debug]
dump_on_error = true
metrics_name = "api_gateway"

[nats]
server = "nats://hyp:4222"
topic = "command.ingress"
timeout = 10
