# Full app config
[auth]
auth_enabled = false

[http]
auth_file = "/tmp/app.json"
pem_file = "/tmp/token_jwt_key.pem"
port = 8084

body_limit = "4K"
max_rps = 20

allow_timeout = false
timeout = 300

allow_compress = false
compress_level = 5

allow_logging = false

[debug]
dump_on_error = false
log_output = "console"
log_verbosity = "debug"
metrics_name = "api_gateway"

[ajc]
task_timeout_min = 3

[ajc.ingress]
concurrency = 4
context = "AJC"
metrics_port = 8090
name = "PING"
topic = "sdk::ec2"

[ajc.egress]
concurrency = 4
context = "AJC"
metrics_port = 8091
name = "PONG"
topic = "sdk::ec2"
