# Full app config
[grpc]
allow_reflection = false
cert_file = "./certs/server.pem"
key_file = "./certs/server.key"
port = 50051
tls_enabled = true

[http]
auth_file = "/tmp/app.json"
pem_file = "/tmp/token_jwt_key.pem"
port = 8084

body_limit = "4K"
max_rps = 100

allow_timeout = false
timeout = 300

allow_compress = false
compress_level = 5

allow_logging = false

[debug]
dump_on_error = false
log_output = "console"
log_verbosity = "debug"
metrics_name = "api_gateway"

[ajc]
concurrency = 8
task_deadline_min = 10
topic = "sdk::ec2"

[ajc.ingress]
metrics_port = 8090
name = "PING"

[ajc.egress]
metrics_port = 0
name = "PONG"

[sdk]
job_time_sec = 240
kv_bucket_name = "ec2buck"
