openapi: 3.0.3
info:
  title: NWS Cloud Control API
  description: OAPI for Cloud Control
  version: v0.0.1
servers:
  - url: http://localhost:8083
paths:
  /metrics:
    get:
      responses:
        "200":
          description: metrics response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Metrics"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1:
    post:
      tags:
        - main
      summary: Cloud Control Request
      requestBody:
        description: CC request body
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Req"

      responses:
        "201":
          description: CC valid response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"

        "500":
          $ref: "#/components/responses/ServerError"

components:
  responses:
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Req:
      type: object
      properties:
        Mandatory:
          $ref: "#/components/schemas/Mandatory"
        Options:
          $ref: "#/components/schemas/Options"
      required:
        - Mandatory

    Mandatory:
      type: object
      properties:
        # Cloud Control Action - CRUDLNR
        Action:
          type: string
          enum:
            - List
            - Create
            - Read
            - Update
            - Delete
            - Nuke
            - Resolve
          x-oapi-codegen-extra-tags:
            validate: required
        # Cloud Control Command - format NWS::EC2::<Command>
        Command:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required
        # Method parameters
        Params:
          type: array
          items:
            type: string
      required:
        - Action
        - Command
        - Params

    Options:
      type: object
      properties:
        # Exclude from action, e.g don't Nuke
        Exclude:
          type: array
          items:
            type: string

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message

    Success:
      type: object
      properties:
        jobid:
          type: string
        err:
          type: string
        data:
          type: string
          format: byte
      required:
        - jobid
        - err
        - data
    Metrics:
      type: array
      items:
        type: string
